resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions: #The list of that exception that will trigger a retry
          - com.pdev.keycloakservice.exception.FeignCustomException

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
  instance:
    prefer-ip-address: true

spring:
  cloud:
#    consul:
#      host: ${CONSUL_SERVER_ADDRESS:localhost}
#      port: 8500
#      discovery:
#        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true

  profiles:
    active: prod
  application:
    name: pdev-keycloak-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      enabled: true
      application: ${spring.application.name}

